# Generated by Django 6.0.2 on 2026-02-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
