# Generated by Django 6.0.2 on 2026-02-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_cart',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
